version: '3.8'
services:
  attendance-app-jenkins:
    image: node:20-alpine
    container_name: attendance_web_jenkins
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/jenkins/workspace/Attendance:/app
    working_dir: /app
    # This completely wipes the slate clean before installing
    command: sh -c "rm -rf node_modules .next package-lock.json && npm install && npm run build && npm start"
    environment:
      - MONGODB_URI=mongodb://db-jenkins:27017/student-attendance
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - db-jenkins

  db-jenkins:
    image: mongo:latest
    container_name: attendance_db_jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-jenkins:/data/db

volumes:
  mongo-data-jenkins:
