version: '3.8'
services:
  attendance-app-jenkins:
    image: node:20-alpine
    container_name: attendance_web_jenkins
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/jenkins/workspace/Attendance:/app
    working_dir: /app
    # We delete any broken configs and generate a perfect one dynamically
    command: sh -c "rm -rf node_modules .next package-lock.json next.config.* && echo 'export default {};' > next.config.mjs && npm install && npm install next react react-dom && npx next build && npx next start"
    environment:
      - MONGODB_URI=mongodb://db-jenkins:27017/student-attendance
    depends_on:
      - db-jenkins

  db-jenkins:
    image: mongo:latest
    container_name: attendance_db_jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-jenkins:/data/db

volumes:
  mongo-data-jenkins:
